[theme]
primaryColor = "#21c154"    # Light Green
backgroundColor = "#1B1B1B" # Dark Gray
secondaryBackgroundColor = "#303134" # Medium Gray
textColor = "#FFFFFF"       # Light Gray
font = "sans serif"
